--!strict
-- The single seam where tunable numbers live. Starts as a hardcoded table;
-- its interface stays identical if that table is later generated by an
-- offline/external training process and dropped in as data. See
-- ARCHITECTURE.md section 8. Nothing in Reasoner.lua should ever need to
-- change for that swap to happen.

local WeightProvider = {}

-- Placeholder defaults. Real numbers are game-specific and unset here on
-- purpose rather than guessed.
local defaultWeights: { [string]: number } = {}

function WeightProvider.get(actionId: string): number
	return defaultWeights[actionId] or 1.0
end

function WeightProvider.set(actionId: string, weight: number)
	defaultWeights[actionId] = weight
end

-- Reserved for later: WeightProvider.loadFromTable(data) so an externally
-- produced weight table can be hot-swapped in without touching this module's
-- callers. Left unimplemented until there's a real format to load.

return WeightProvider
