"""Occlusion repair by symmetry-group closure.

The task family: a structured grid has part of it blanked out with a marker
colour, and the answer is either the repaired grid or just the missing patch.

Method.  Collect a candidate set of cell-permutations (mirrors about every
half-integer axis, translations by every period, and -- for square grids --
the diagonals).  Keep a permutation only if it never contradicts an observed
cell and is supported by enough overlap.  Union-find over the surviving
permutations yields the orbit partition; because union-find closes under
composition, we recover the *whole group* generated by the accepted maps
without having to enumerate it.  Every orbit containing at least one observed
cell is then determined.
"""

from collections import Counter

from .. import grid as G
from ..task import Hyp

SOLVER = "symmetry"
MIN_SUPPORT = 0.30


def _h(n, f, c):
    return Hyp(n, f, c, SOLVER)


class _DSU:
    __slots__ = ("p",)

    def __init__(self, n):
        self.p = list(range(n))

    def find(self, x):
        p = self.p
        while p[x] != x:
            p[x] = p[p[x]]
            x = p[x]
        return x

    def union(self, a, b):
        ra, rb = self.find(a), self.find(b)
        if ra != rb:
            self.p[rb] = ra


def _candidate_maps(h, w):
    """Yield (name, fn(r, c) -> (r, c) or None)."""
    maps = []
    for a in range(1, 2 * w - 2):
        maps.append(("mh%d" % a, (lambda a: lambda r, c: (r, a - c))(a)))
    for a in range(1, 2 * h - 2):
        maps.append(("mv%d" % a, (lambda a: lambda r, c: (a - r, c))(a)))
    for p in range(1, h):
        maps.append(("tr%d" % p, (lambda p: lambda r, c: (r + p, c))(p)))
    for q in range(1, w):
        maps.append(("tc%d" % q, (lambda q: lambda r, c: (r, c + q))(q)))
    # Diagonal translations.  A grid whose colour depends on (r+c) mod k or
    # (r-c) mod k is invariant under these and under nothing else in the list,
    # so without them every diagonally striped pattern is unrepairable.
    for p in range(1, min(h, w)):
        maps.append(("td%d" % p, (lambda p: lambda r, c: (r + p, c + p))(p)))
        maps.append(("ta%d" % p, (lambda p: lambda r, c: (r + p, c - p))(p)))
    if h == w:
        maps.append(("diag", lambda r, c: (c, r)))
        maps.append(("adiag", (lambda n: lambda r, c: (n - c, n - r))(h - 1)))
        maps.append(("rot90", (lambda n: lambda r, c: (c, n - r))(h - 1)))
    return maps


def _repair(g, unknown, strict=True, min_support=MIN_SUPPORT):
    h, w = G.dims(g)
    n = h * w
    known = [g[r][c] != unknown for r in range(h) for c in range(w)]
    nk = sum(known)
    if nk == n or nk < 4:
        return None
    dsu = _DSU(n)
    accepted = 0
    for _name, f in _candidate_maps(h, w):
        pairs = 0
        bad = False
        links = []
        for r in range(h):
            base = r * w
            for c in range(w):
                t = f(r, c)
                if t is None:
                    continue
                tr, tc = t
                if not (0 <= tr < h and 0 <= tc < w):
                    continue
                i = base + c
                j = tr * w + tc
                if i >= j:
                    continue
                links.append((i, j))
                if known[i] and known[j]:
                    pairs += 1
                    if g[r][c] != g[tr][tc]:
                        bad = True
                        break
            if bad:
                break
        if bad or pairs < max(6, int(min_support * nk)):
            continue
        accepted += 1
        for i, j in links:
            dsu.union(i, j)
    if not accepted:
        return None
    vals = {}
    for i in range(n):
        if known[i]:
            root = dsu.find(i)
            v = g[i // w][i % w]
            prev = vals.get(root)
            if prev is None:
                vals[root] = v
            elif prev != v:
                return None
    out = [[g[r][c] for c in range(w)] for r in range(h)]
    for i in range(n):
        if not known[i]:
            v = vals.get(dsu.find(i))
            if v is None:
                if strict:
                    return None
                continue
            out[i // w][i % w] = v
    return tuple(tuple(r) for r in out)


def _occluded_bbox(g, unknown):
    cells = [(r, c) for r, row in enumerate(g) for c, v in enumerate(row)
             if v == unknown]
    if not cells:
        return None
    return G.bbox_of(cells)


def _patch(g, unknown, strict=True):
    rep = _repair(g, unknown, strict)
    if rep is None:
        return None
    bb = _occluded_bbox(g, unknown)
    if bb is None:
        return None
    return G.subgrid(rep, *bb)


# --------------------------------------------------------------------------

def _unknown_candidates(ctx):
    """Colours plausibly acting as the "hole" marker."""
    cands = Counter()
    if ctx.same_shape:
        for a, b in ctx.train:
            diff = set()
            for ra, rb in zip(a, b):
                for x, y in zip(ra, rb):
                    if x != y:
                        diff.add(x)
            if len(diff) == 1:
                cands[diff.pop()] += 1
    else:
        for a, b in ctx.train:
            bh, bw = G.dims(b)
            for c in G.palette(a):
                bb = _occluded_bbox(a, c)
                if bb and (bb[2] - bb[0] + 1, bb[3] - bb[1] + 1) == (bh, bw):
                    cands[c] += 1
    got = [c for c, n in cands.items() if n == len(ctx.train)]
    if got:
        return got
    return [c for c, _n in cands.most_common(3)]


def generate(ctx):
    res = []
    cands = _unknown_candidates(ctx)
    if not cands:
        # still worth trying the task background as a hole marker
        cands = [ctx.bg]
    for u in cands[:4]:
        for strict in (True, False):
            sfx = "" if strict else "_lax"
            res.append(_h("repair#%d%s" % (u, sfx),
                          (lambda u, s: lambda g: _repair(g, u, s))(u, strict),
                          3.0 if strict else 4.0))
            res.append(_h("patch#%d%s" % (u, sfx),
                          (lambda u, s: lambda g: _patch(g, u, s))(u, strict),
                          3.2 if strict else 4.2))
        res.append(_h("repair_loose#%d" % u,
                      (lambda u: lambda g: _repair(g, u, True, 0.12))(u), 5.0))
        res.append(_h("patch_loose#%d" % u,
                      (lambda u: lambda g: _patch(g, u, True))(u), 5.2))
    return res
