-- The system's record of how it got here.
--
-- Three artefacts, deliberately separate because they answer different questions:
--
--   data/corpus.jsonl   The training data. One line per task the system has ever solved: the task's
--                       family and feature bucket, the program it found, what the generator actually
--                       used, and the generation it happened in. This is the evidence every mutation
--                       operator learns from -- library learning, anti-unification and prior fitting
--                       all read this corpus and nothing else -- so it is the closest thing the
--                       system has to a training set. The generator's own expression is recorded for
--                       the reader only; the solver never sees it (see tasks.solver_view).
--
--   data/journal.jsonl  The milestones. Every accepted change with its evidence, every benchmark
--                       rotation, every research fetch, and the challenge ranking at that moment.
--                       Machine-readable, append-only, one JSON object per line.
--
--   JOURNAL.md          The same milestones rendered for a human, regenerated each generation.
--
-- The per-candidate verdicts stay in state/lineage.jsonl. That file answers "what was tried and why
-- was it refused"; this one answers "what changed and what did it cost to find out".
local json = require("rsi.kernel.json")
local M = {}

function M.record(root, entry)
  entry.time = entry.time or os.time()
  json.append_line(root .. "/data/journal.jsonl", entry)
end

function M.add_corpus(root, rows)
  if #rows == 0 then return 0 end
  local f = io.open(root .. "/data/corpus.jsonl", "a")
  if not f then return 0 end
  for _, r in ipairs(rows) do f:write(json.encode(r), "\n") end
  f:close()
  return #rows
end

function M.corpus_size(root)
  local n = 0
  local f = io.open(root .. "/data/corpus.jsonl", "r")
  if not f then return 0 end
  for _ in f:lines() do n = n + 1 end
  f:close()
  return n
end

local function pct(x) return string.format("%.1f%%", 100 * (x or 0)) end

-- Render the human-readable ledger. Kept short at the top (where the system stands) and long at the
-- bottom (how it got there), because the first question is usually "is it working".
function M.render(root, ctx)
  local entries = json.read_lines(root .. "/data/journal.jsonl")
  local out = {}
  local function w(s) out[#out + 1] = s end

  w("# CELL4 journal")
  w("")
  w("Auto-generated by `rsi/kernel/journal.lua` at the end of every generation. Do not edit; edits are")
  w("overwritten. The machine-readable form is `rsi/data/journal.jsonl`, the per-candidate verdicts are")
  w("in `rsi/state/lineage.jsonl`, and the solved-program corpus the operators learn from is")
  w("`rsi/data/corpus.jsonl`.")
  w("")
  w("## Where it stands")
  w("")
  w(string.format("* generation **%d**, champion `%s`", ctx.gen, ctx.fingerprint or "?"))
  w(string.format("* held-out **%d/%d** (%s), 95%% CI %s – %s, on secret-salted tasks of epoch %d",
    ctx.heldout.solved, ctx.heldout.n, pct(ctx.heldout.rate), pct(ctx.heldout.lo), pct(ctx.heldout.hi),
    ctx.heldout_epoch or 1))
  w(string.format("* adversarial %d/%d, regression %d/%d, external ARC %s",
    ctx.adversarial.solved, ctx.adversarial.n, ctx.regression.solved, ctx.regression.n,
    ctx.external.n > 0 and (ctx.external.solved .. "/" .. ctx.external.n) or "none fetched yet"))
  w(string.format("* %d of %d candidates accepted across the whole run", ctx.accepted_total, ctx.candidates_total))
  w(string.format("* solved-program corpus: **%d** entries", ctx.corpus_size or 0))
  w(string.format("* learned library: %d abstractions, visible operators: %d", ctx.library_size or 0, ctx.ops or 0))
  w("")

  if ctx.challenge and #ctx.challenge > 0 then
    w("## What is worth being challenged by, right now")
    w("")
    w("Ranked by the system's own measurements. `information` is 4p(1-p) on the solve rate, so it peaks")
    w("where the family is solved about half the time; `discrim` is how often candidates actually differ")
    w("from the champion there, which is the benchmark's power to detect an improvement at all;")
    w("`headroom` is mean partial credit on the tasks it fails. A family it never solves scores low on")
    w("purpose -- difficulty alone is not the objective, telling improvement from noise is.")
    w("")
    w("| family | n | solved | information | discrim | headroom | score |")
    w("|---|---|---|---|---|---|---|")
    for i, r in ipairs(ctx.challenge) do
      if i > 14 then break end
      w(string.format("| `%s` | %d | %s | %.2f | %.2f | %.2f | **%.3f** |",
        r.family, r.n, pct(r.solve_rate), r.information, r.discrimination, r.headroom, r.score))
    end
    w("")
    if ctx.saturated and #ctx.saturated > 0 then
      w("Saturated (nearly always solved *and* no longer separating candidates): `"
        .. table.concat(ctx.saturated, "`, `") .. "`. These get harder variants spawned from them.")
      w("")
    end
  end

  local accepted, rotations, research = {}, {}, {}
  for _, e in ipairs(entries) do
    if e.kind == "accepted" then accepted[#accepted + 1] = e
    elseif e.kind == "rotation" then rotations[#rotations + 1] = e
    elseif e.kind == "research" then research[#research + 1] = e end
  end

  w("## Levels reached")
  w("")
  if #accepted == 0 then
    w("No candidate has yet cleared the acceptance rule. That is the honest state, not a placeholder:")
    w("a change is retained only when its paired held-out gain is significant under **both** the")
    w("bootstrap and the exact sign test, it loses nothing on the regression suite, and it does not")
    w("drop on the fresh adversarial split. Every attempt and its numbers are in `state/lineage.jsonl`.")
  else
    w("| gen | operator | change | held-out | evidence |")
    w("|---|---|---|---|---|")
    for i = #accepted, math.max(1, #accepted - 40), -1 do
      local e = accepted[i]
      w(string.format("| %d | `%s` | %s | %s → %s | %s |", e.gen, e.operator, e.change,
        pct(e.before), pct(e.after), e.reason))
    end
  end
  w("")

  if #rotations > 0 then
    w("## Benchmark rotations")
    w("")
    w("When one family drives repeated acceptances, the secret held-out salt is replaced, new motifs")
    w("enter the world, and a harder variant of that family is spawned. This is what stops the system")
    w("from optimising against a fixed test set.")
    w("")
    for i = #rotations, math.max(1, #rotations - 20), -1 do
      local e = rotations[i]
      w(string.format("* **gen %d** — %s", e.gen, e.detail))
    end
    w("")
  end

  if #research > 0 then
    w("## Research fetches")
    w("")
    for i = #research, math.max(1, #research - 12), -1 do
      local e = research[i]
      w(string.format("* **gen %d** — %d new papers, %d new ARC tasks%s", e.gen or 0,
        e.papers_new or 0, e.arc_new or 0,
        (e.errors and e.errors > 0) and (" (" .. e.errors .. " fetch errors)") or ""))
    end
    w("")
  end

  w("## How to read a rejection")
  w("")
  w("Most candidates are rejected and that is the harness working. `screened out on held-out` means the")
  w("candidate solved strictly fewer held-out tasks, so it cannot pass any acceptance clause and the")
  w("remaining splits were not run. `not significant` means it gained but the gain is inside the noise")
  w("-- on 200 held-out tasks a candidate needs roughly nine wins against at most one loss to clear")
  w("p<0.05 on both tests. `regression: lost N` means it broke something a previous champion could do.")

  local f = assert(io.open(root .. "/../JOURNAL.md", "w"))
  f:write(table.concat(out, "\n"), "\n")
  f:close()
end

return M
